### ISSUE TITLE
Turn off music without so many #IFNDEF macros

### ISSUE THREAD

**Issue by thomasballinger** [thomasballinger/endless-web#10]
I can't find it now but I believe @tehhowch suggested using command line flags instead of ifdefs to turn off features. Will check again, but if this is still the case then we need to mock out the functions provided mad.h (so it still compiles, though it won't work) and a command line flags to decide whether to start the music threads.

**Comment by janisozaur** [comment]
You would need to either select the backend at compile time (at least for linking) or rely on `dlopen`-ing the library, neither of those sound immediately as improvements - can you provide more details?

**Comment by thomasballinger** [comment]
That makes sense, maybe we don't want to do this.

**Comment by thomasballinger** [comment]
See discussion at https://github.com/endless-sky/endless-sky/pull/6159 and implementations in https://github.com/endless-sky/endless-sky/pull/6163 and https://github.com/endless-sky/endless-sky/pull/6164. The ideal solution is just not turning off music, so either compiling libmad with emscripten or using a different mp3 decoder solution.
