### ISSUE TITLE
Measure data transfer

### ISSUE THREAD

**Issue by thomasballinger** [thomasballinger/endless-web#19]
It's hard for me to tell from the Chrome dev tools whether assets are being loaded multiple times, but I suspect they are:
![image](https://user-images.githubusercontent.com/458879/128606143-14c826d1-3832-4116-922e-ba204bd6e6fe.png)

**Comment by janisozaur** [comment]
That's odd, to say the least. What and why would load it multiple times? Is it perhaps due to loading assets and only loading parts of it from the data file? But that doesn't explain so many js file loads

**Comment by thomasballinger** [comment]
I think loading piece by piece with feth (for the progress bar) may be causing caching not to work right

**Comment by thomasballinger** [comment]
Fixed by https://github.com/thomasballinger/endless-web/pull/33
![image](https://user-images.githubusercontent.com/458879/134390781-0bd6b455-7b25-407d-bd2b-39a27fb4b734.png)
