### ISSUE TITLE
Crash on pinch-to-zoom in Firefix on Android

### ISSUE THREAD

**Issue by thomasballinger** [thomasballinger/endless-web#22]
![](https://files.catbox.moe/z69mj2.jpeg)

**Comment by Pilcrow182** [comment]
This was my issue, thanks Thomas for filing it for me. This crash happened shortly after _ending_ the first conversation with the old man, while I was sitting in the main planet/dock screen.

**Comment by Pilcrow182** [comment]
Aha! After playing around with it a bit more, I think I've found the cause. I must've bumped the screen and activated Android's pinch-to-zoom feature; tried it on a whim, and it crashes every time (though, oddly enough, the error message seems to have different line numbers each time)...

![Screenshot_2021-08-09-01-28-32-145](https://user-images.githubusercontent.com/6181009/128667780-fb2db382-6e6a-48de-a4bf-2a95b7966b7d.jpeg)

**Comment by thomasballinger** [comment]
@Pilcrow182 oh interesting, something about touch handling. Do things work for you otherwise?

**Comment by Pilcrow182** [comment]
@thomasballinger everything else seems to work, yes. Starting it up again, I was able to play until the end of the tutorial, engage in combat, and equip some new outfits just fine.

There _does_ seem to be a GUI scaling problem as well, but that's a separate issue...

**Comment by thomasballinger** [comment]
This seems to have been fixed by a meta tag? Closing but let's reopen if not.
