### ISSUE TITLE
[SOLVED] Fonts not working in Firefox-ESR 91.0 on Ubuntu Budgie 20.04

### ISSUE THREAD

**Issue by noalternative67** [thomasballinger/endless-web#36]
![Screenshot from 2022-04-27 08-40-04](https://user-images.githubusercontent.com/58873344/165635982-f8d872ff-08ae-434a-aadc-15897c91c57b.png)

I tried to fix it by installing microsoft fonts on my device.   They load and work on all other websites I have tried, but this game.

The problem was caused by some anti-browser finger print setting in about:config

https://support.mozilla.org/en-US/questions/1283036

This setting does two things.   

1)It changes the useragent from firefox/linux to firefox/windows10 &
2)It won't tell the website what fonts you have available.

I would say the later probably messed up you site.   It is all good now;)

![Screenshot from 2022-04-28 21-09-01](https://user-images.githubusercontent.com/58873344/165875389-bc57c22f-af26-41ff-9078-69af908aec61.png)

**Comment by thomasballinger** [comment]
What browser and platform is this?

**Comment by noalternative67** [comment]
Firefox ESR https://support.mozilla.org/en-US/kb/switch-to-firefox-extended-support-release-esr
Ubuntu Budgie Linux 20.04 https://ubuntubudgie.org/

**Comment by noalternative67** [comment]
Here is the Ubuntu PPA for Firefox-ESR https://launchpad.net/~mozillateam/+archive/ubuntu/ppa
